openapi: 3.0.4
info:
  version: '1.0'
  title: "Knowntain OpenAPI 3.0"
  description: APIs for managing geographical and environmental data.
  license:
    name: MIT
servers:
  - url: http://localhost:8080/
    description: Localhost
  #- url: https://knowntain.onrender.com/api/v1
    #description: render.com
paths:
# Register **************************************************************
    /auth/register:
      post:
        summary: Registra un utente
        description: Permette ad un utente di creare un nuovo account
        requestBody:
          required: true
          content:
            application/json:
              schema : {$ref: '#/components/schemas/RegisterRequest'}
        responses: 
          '201':
            description: Registrazione valida
            content:
              application/json:
                schema: {$ref: '#/components/schemas/AuthResponse'}
          '400':
            description: Richiesta non valida
            content:
              application/json:
                schema: 
                  type: object
                  properties:
                    message: 
                      type: string
                      example: Dati di input non validi
          '409':
            description: Conflitto
            content:
              application/json:
                schema: 
                  type: object
                  properties:
                    message:
                      type: string
                      example: Email o Nickname già in uso
# Login **************************************************************
    /auth/login:
      post:
        summary: Login utente e dipendente
        description: Permette ad un utente o ad un dipendente di accedere alle proprie funzionalità
        requestBody:
          required: true
          content:
            application/json:
              schema : {$ref: '#/components/schemas/LoginRequest'}
        responses: 
          '200':
            description: Login valido
            content:
              application/json:
                schema: {$ref: '#/components/schemas/AuthResponse'}       
          '401':
            description: Login non riuscito
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Email o password non valide
# Segnalazioni Utente ******************************************************
    /segnalazioni:
      get:
        summary: Ritorna le segnalazioni validate
        description: Ritorna un array delle segnalazioni validate
        responses:
          '200':
            description: Segnalazione registrata correttamente
            content:
              application/json:
                schema:
                  type: array
                  items: {$ref: '#/components/schemas/Segnalazione'}










# Components ******************************************************
components:
  schemas:
# RegisterRequest **********************
    RegisterRequest:
      type: object
      required:
        - nome
        - cognome
        - email
        - nickname
        - password
      properties:
        nome:
          type: string
          example: Mario
        cognome:
          type: string
          example: Rossi
        email:
          type: string
          format: email
          example: mario.rossi@example.com
        nickname:
          type: string
          example: supermario
        password:
          type: string
          format: password
          minLength: 8
          example: P4ssw0rd!
# LoginRequest **********************
    LoginRequest:
      type: object
      required:
        - email
        - password
        - ruolo
      properties:
        email:
            type: string
            format: email
            example: mario.rossi@example.com
        password:
            type: string
            format: password
            minLength: 8
            example: P4ssw0rd!
        ruolo: 
          type: string
          enum: 
            - utente
            - dipendente
          example: dipendente
# AuthResponse **********************
    AuthResponse:
      type: object
      required:
        - success
        - message
        - token
        - id
        - email
        - self
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Enjoy your token!
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        id:
          type: string
          example: "123"
        email:
          type: string
          example: mario.rossi@example.com
        self: 
          type: string
          example: /utenti/123
# GeoJson ************************************
    GeoJSON:
      type: object
      required:
        - type
        - coordinates
      properties:
        type:
          type: string
          enum: [Point, Polygon]
          example: Point
        coordinates:
          type: array
          example: [25.29342133240317, 19.18888491930697]
# Segnalazione **********************
    Segnalazione:
      type: object
      properties:
        id:
          type: string
          example: "123"
        titolo:
          type: string
          example: "Pericolo Frana"
        descrizione:
          type: string
          example: Frana in zona trafficata
        data:
          type: string
          format: date-time
          example: "2025-11-30T15:00:00Z"
        utente_id:
          type: string
          example: "456"
        posizione: {$ref: '#/components/schemas/GeoJSON'}