openapi: 3.0.4
info:
  version: '1.0'
  title: "Knowntain OpenAPI 3.0"
  description: APIs for managing book lendings.
  license:
    name: MIT
servers:
  - url: http://localhost:8080/
    description: Localhost
  #- url: https://knowntain.onrender.com/api/v1
    #description: render.com
paths:
# Register **************************************************************
    /auth/register:
      post:
        summary: Register a user
        description: Allows a user to create a new account.
        requestBody:
          required: true
          content:
            application/json:
              schema : {$ref: '#/components/schemas/RegisterRequest'}
        responses: 
          '201':
            description: Registation successful
            content:
              application/json:
                schema: {$ref: '#/components/schemas/AuthResponse'}
          '400':
            description: Bad request 
            content:
              application/json:
                schema: 
                  type: object
                  properties:
                    message: 
                      type: string
                      example: Invalid input data
          '409':
            description: Conflict
            content:
              application/json:
                schema: 
                  type: object
                  properties:
                    message:
                      type: string
                      example: Email already in use
# Login **************************************************************
    /auth/login:
      post:
        summary: Log in a user
        description: Enables a user to access their own features
        requestBody:
          required: true
          content:
            application/json:
              schema : {$ref: '#/components/schemas/LoginRequest'}
        responses: 
          '200':
            description: Login successful
            content:
              application/json:
                schema: {$ref: '#/components/schemas/AuthResponse'}       
          '401':
            description: Login unsuccesful
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Invalid email or password
# Segnalazioni Utente ******************************************************
    /segnalazioni:
      get:
        summary: Ritorna le segnalazioni validate
        description: Ritorna un array delle segnalazioni validate
        responses:
          '200':
            description: Successful
            content:
              application/json:
                schema:
                  type: array
                  items: {$ref: '#/components/schemas/Segnalazione'}










# Components ******************************************************
components:
  schemas:
# RegisterRequest **********************
    RegisterRequest:
      type: object
      required:
        - name
        - surname
        - email
        - nickname
        - password
      properties:
        name:
          type: string
          example: Mario
        surname:
          type: string
          example: Rossi
        email:
          type: string
          format: email
          example: mario.rossi@example.com
        nickname:
          type: string
          example: supermario
        password:
          type: string
          format: password
          minLength: 8
          example: P4ssw0rd!
# LoginRequest **********************
    LoginRequest:
      type: object
      required:
        - email
        - password
        - role
      properties:
        email:
            type: string
            format: email
            example: mario.rossi@example.com
        password:
            type: string
            format: password
            minLength: 8
            example: P4ssw0rd!
        role: 
          type: string
          enum: 
            - utente
            - dipendente
          example: dipendente
# AuthResponse **********************
    AuthResponse:
      type: object
      required:
        - message
        - token
        - user
      properties:
        message:
          type: string
          example: Login successful
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        user:
          type: object
          properties:
            id:
              type: string
              example: "123"
            email:
              type: string
              example: mario.rossi@example.com
# GeoJson ************************************
    GeoJSON:
      type: object
      required:
        - type
        - coordinates
      properties:
        type:
          type: string
          enum: [Point, Polygon]  # aggiungi altri tipi se vuoi
          example: Point
        coordinates:
          type: array
          example: [25.29342133240317, 19.18888491930697]
# Segnalazione **********************
    Segnalazione:
      type: object
      properties:
        id:
          type: string
          example: "123"
        titolo:
          type: string
          example: "Pericolo Frana"
        descrizione:
          type: string
          example: Frana in zona trafficata
        data:
          type: string
          format: date-time
          example: "2025-11-30T15:00:00Z"
        utente_id:
          type: string
          example: "456"
        posizione: {$ref: '#/components/schemas/GeoJSON'}